---
- hosts: node
  become: yes
  tasks:
  - name: create multiple files
    file:
      path: "{{ item }}"
      state: touch
      mode: "0664"
    with_items:
      - /tmp/f1
      - /tmp/f2
      - /tmp/f3
    
