---
- hosts: node
  gather_facts: no
  become: yes
  tasks:
  - name: Uninstall the httpd service
    yum:
      name: httpl
      state: removed
  - name: Download a sample file
    get_url:
      url: https://file-examples-com.github.io/uploads/2017/02/file-sample_100kB.doc
      dest: /tmp/sample_file.doc
      mode: '0440'
  - name: Disabling the selinux
    selinux:
      state: disabled

